weather:
  latitude: 41.9028
  longitude: 12.4964
  variables:
    - temperature_2m
    - precipitation
    - windspeed_10m

  azure:
    container_name: "weather-raw"
    blob_prefix: "weather"

paths:
  raw_data_weather: "data/raw/weather"
  raw_data_mobility: "data/raw/mobility_rome_taxi"

mobility:
  azure:
    container_name: "data"
    blob_path: "external/rome_taxi/taxi_february.tar.gz"

  local:
    external_dir: "data/external/rome_taxi"
    archive_name: "taxi_february.tar.gz"
    extracted_subdir: "extracted"
